--
-- Name: add_data_file_requests; Type: TABLE;
--

CREATE TABLE if not exists add_data_file_requests (
       id bigint NOT NULL,
       created_at date NOT NULL,
       link_to_file text NOT NULL,
       name text NOT NULL,
       user_id bigint NOT NULL,
       status bigint NOT NULL,
       moderator_id bigint,
       data_set_id bigint NOT NULL
);

alter table add_data_file_requests
    alter column id add generated by default as identity;

--
-- Name: data_sets; Type: TABLE;
--

CREATE TABLE if not EXISTS data_sets (
          id bigint NOT NULL,
          updated_at date NOT NULL,
          created_at date NOT NULL,
          tag_id bigint,
          name text NOT NULL,
          owner_id bigint NOT NULL
);

alter table data_sets
    alter column id add generated by default as identity;

--
-- Name: data_files; Type: TABLE;
--

CREATE TABLE if not exists data_files (
           id bigint NOT NULL,
           name text NOT NULL,
           updated_at date NOT NULL,
           created_at date NOT NULL,
           data_set_id bigint NOT NULL,
           link_to_file text NOT NULL,
           owner_id bigint NOT NULL
);

alter table data_files
    alter column id add generated by default as identity;

--
-- Name: edit_data_file_requests; Type: TABLE;
--

CREATE TABLE if NOT EXISTS edit_data_file_requests (
        id bigint NOT NULL,
        user_id bigint NOT NULL,
        status bigint NOT NULL,
        moderator_id bigint,
        data_file_id bigint NOT NULL,
        updated_at date NOT NULL,
        link_to_file text NOT NULL,
        name text NOT NULL
);

alter table edit_data_file_requests
    alter column id add generated by default as identity;

--
-- Name: request_statuses; Type: TABLE;
--

CREATE TABLE request_statuses (
     id bigint NOT NULL,
     name text NOT NULL
);

alter table request_statuses
    alter column id add generated by default as identity;

--
-- Name: role_change_requests; Type: TABLE;
--

CREATE TABLE role_change_requests (
     id bigint NOT NULL,
     user_id bigint NOT NULL,
     moderator_id bigint,
     status bigint NOT NULL,
     processed_at date
);

alter table role_change_requests
    alter column id add generated by default as identity;

--
-- Name: roles; Type: TABLE;
--

CREATE TABLE roles (
      id bigint NOT NULL,
      name text NOT NULL
);

alter table roles
    alter column id add generated by default as identity;

--
-- Name: tags; Type: TABLE;
--

CREATE TABLE tags (
     id bigint NOT NULL,
     name text NOT NULL,
     main_tag bigint
);

alter table tags
    alter column id add generated by default as identity;

--
-- Name: users; Type: TABLE;
--

CREATE TABLE users (
      id bigint NOT NULL,
      role bigint NOT NULL,
      first_name text NOT NULL,
      last_name text NOT NULL,
      email text NOT NULL,
      password text NOT NULL
);

alter table users
    alter column id add generated by default as identity;

--
-- Type: CONSTRAINTs;
--

ALTER TABLE ONLY add_data_file_requests
    ADD CONSTRAINT add_data_file_requests_pk PRIMARY KEY (id);

ALTER TABLE ONLY data_files
    ADD CONSTRAINT data_file_pk PRIMARY KEY (id);

ALTER TABLE ONLY data_sets
    ADD CONSTRAINT dataset_pk PRIMARY KEY (id);

ALTER TABLE ONLY edit_data_file_requests
    ADD CONSTRAINT edit_data_file_requests_pk PRIMARY KEY (id);

ALTER TABLE ONLY request_statuses
    ADD CONSTRAINT request_statuses_pk PRIMARY KEY (id);

ALTER TABLE ONLY role_change_requests
    ADD CONSTRAINT role_change_requests_pk PRIMARY KEY (id);

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_pk PRIMARY KEY (id);

ALTER TABLE ONLY tags
    ADD CONSTRAINT tags_pk PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT user_pk PRIMARY KEY (id);

--
-- Type: FK CONSTRAINTs;
--

ALTER TABLE ONLY add_data_file_requests
    ADD CONSTRAINT add_data_file_requests_data_sets_id_fk FOREIGN KEY (data_set_id) REFERENCES data_sets(id);

ALTER TABLE ONLY add_data_file_requests
    ADD CONSTRAINT add_data_file_requests_request_statuses_id_fk FOREIGN KEY (status) REFERENCES request_statuses(id);

ALTER TABLE ONLY add_data_file_requests
    ADD CONSTRAINT add_data_file_requests_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY add_data_file_requests
    ADD CONSTRAINT add_data_file_requests_users_id_fk_2 FOREIGN KEY (moderator_id) REFERENCES users(id);

ALTER TABLE ONLY data_files
    ADD CONSTRAINT data_file_data_set_id_fk FOREIGN KEY (data_set_id) REFERENCES data_sets(id);

ALTER TABLE ONLY data_files
    ADD CONSTRAINT data_files_fk_owner FOREIGN KEY (owner_id) REFERENCES users(id);

ALTER TABLE ONLY data_sets
    ADD CONSTRAINT data_set_fk FOREIGN KEY (tag_id) REFERENCES tags(id);

ALTER TABLE ONLY data_sets
    ADD CONSTRAINT data_sets_fk_owner FOREIGN KEY (owner_id) REFERENCES users(id);

ALTER TABLE ONLY edit_data_file_requests
    ADD CONSTRAINT edit_data_file_requests_data_files_id_fk FOREIGN KEY (data_file_id) REFERENCES data_files(id);

ALTER TABLE ONLY edit_data_file_requests
    ADD CONSTRAINT edit_data_file_requests_request_statuses_id_fk FOREIGN KEY (status) REFERENCES request_statuses(id);

ALTER TABLE ONLY edit_data_file_requests
    ADD CONSTRAINT edit_data_file_requests_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY edit_data_file_requests
    ADD CONSTRAINT edit_data_file_requests_users_id_fk_2 FOREIGN KEY (moderator_id) REFERENCES users(id);

ALTER TABLE ONLY role_change_requests
    ADD CONSTRAINT request_status_moderator_id_fk FOREIGN KEY (moderator_id) REFERENCES users(id);

ALTER TABLE ONLY role_change_requests
    ADD CONSTRAINT request_status_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY role_change_requests
    ADD CONSTRAINT role_change_request_status_fk FOREIGN KEY (status) REFERENCES request_statuses(id);

ALTER TABLE ONLY users
    ADD CONSTRAINT user_fk FOREIGN KEY (role) REFERENCES roles(id);

--
-- Type: TABLEs DATA;
--

insert into request_statuses (id, name) values (default,'Not processed');
insert into request_statuses (id, name) values (default,'Confirmed');
insert into request_statuses (id, name) values (default,'Declined');

insert into roles (id, name) values (default,'user');
insert into roles (id, name) values (default,'moderator');

insert into tags (id, name) values (default,'all');

insert into users (id, role, first_name, last_name, email, password) values (default, 2, 'admin', 'admin', 'admin@admin.com', '$2a$10$iWOIpv08YdHeiemEEOqm/O3QHvYtjdBn6azEIipixYe7hoA6rRhxa');

insert into data_sets (id, updated_at, created_at, tag_id, name, owner_id) values (default, now(), now(), 1, 'Init', 1);
